server:
  port: 80

spring:
  application:
    name: cinema-reserve

  datasource:
    url: jdbc:mysql://localhost:3306/Cinema_Reserve?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: madihaazamahmed@gmail.com
    password: cdza kuwj exqg xlxw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

admin:
  email: admin@gmail.com
  password: admin

cloudinary:
  url: "cloudinary://247155759945484:k7YVlB-e-hYm4y1_Gg1OaR8k26c@dby8t7vut"
